### ISSUE TITLE
Correct Syntax for Importing Modules into Python

### ISSUE THREAD

**Issue by cschiri** [LastShekel/ITMO_FS#32]
I pip installed the ITMO_FS package via PyPi yesterday (9 April 2020).

I am having issues with importing the "AddDelWrapper" and "BackwardSelection" wrappers. To import the modules, I used the following commands:

```
from skfeature.function.statistical_based import gini_index
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.svm import SVC
import ITMO_FS
from ITMO_FS.filters import *
from ITMO_FS.hybrid.Melif import Melif
from ITMO_FS.wrappers import AddDelWrapper
from ITMO_FS.wrappers import BackwardSelection
```

The imports occur without issues. But, when I try to perform the feature selection using this code:

```
# Select Features Using Logistic Regression and Add-Del 

lr = LogisticRegression()
wrapper = AddDelWrapper(lr, f1_score)
wrapper.fit(X, Y)
print(wrapper.best_score)
```
I get this error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-56-fc0101df9b58> in <module>
      2 
      3 lr = LogisticRegression()
----> 4 wrapper = AddDelWrapper(lr, f1_score)
      5 wrapper.fit(X, Y)
      6 print(wrapper.best_score)

TypeError: 'module' object is not callable
```

This implies that I may not be using the correct syntax to import the module. Could you please advise on the correct syntax? I could not find anything in the package repository that addresses these basics or examples of the correct usage of the module.

Clarity is needed...

**Comment by LastShekel** [comment]
Hello!
Thank you for your observation.
Yes,in current version you are not using this correctly(in terms of version).
Correct way is to import following:
`from ITMO_FS.wrappers.AddDelWrapper import Add_del
from ITMO_FS.wrappers.BackwardSelection import BackwardSelection`
And be careful because Add_del doesn't have fit, it has run method(this has already been corrected in develop version)
This friday(17.04.2020) we will update library in pypi repository with new methods and large fixes.
If you want to get the code immediately, i suggest you to take a look at [develop branch](https://github.com/LastShekel/ITMO_FS/tree/develop) or this [file](https://github.com/LastShekel/ITMO_FS/blob/develop/ITMO_FS/wrappers/deterministic/AddDelWrapper.py) to copy code directly in your project

**Comment by LastShekel** [comment]
Issue closed due fix with new version
